###########################################################################
# System Information
###########################################################################

sysLocation Homelab
sysContact Anselem
sysServices 72

###########################################################################
# Agent Listening Address
###########################################################################

agentAddress udp:161,udp6:[::1]:161

###########################################################################
# Access Control
###########################################################################

rocommunity public 127.0.0.1
rocommunity public 192.168.0.0/24

###########################################################################
# AgentX
###########################################################################

master agentx

###########################################################################
# Include extra config files
###########################################################################

includeDir /etc/snmp/snmpd.conf.d
